# Generated by Django 4.1.3 on 2023-01-05 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuarios', '0005_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
